<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE student [
    <!ELEMENT student (name, age, class, fees)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
]> -->
<!DOCTYPE student SYSTEM "file.dtd">
<student>
    <name>hamza</name>
    <age>19</age>
    <class>2nd year</class>
    <fees>10000</fees>
</student>